# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 06:24
from __future__ import unicode_literals

import Blog2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Blog2.models.upload_location),
        ),
    ]
